package main

import "fmt"

func main() {
	// This is a simple Go program that prints "Hello, World!" to the console.
	/*
	The executable file can be generated by running the command `go build hello.go` in the terminal.
	*/
	fmt.Println("Hello, World!")
}